version: "3.9"
services:
  app:
    build: .
    command: npm start
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - devnet

  database:
    image: postgres
    restart: always
    volumes:
      - devdb:/var/lib/postgresql/data
    networks:
      - devnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  devdb:

networks:
  devnet:
