version: "3.9"
services:
  app:
    build: .
    command: npm start
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - devnet

  database:
    image: postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8G'
        reservations:
          cpus: '1'
          memory: '1G'
    volumes:
      - devdb:/var/lib/postgresql/data
    networks:
      - devnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j:
    image: bitnami/neo4j:latest
    networks:
      - devnet
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'

volumes:
  devdb:

networks:
  devnet:
